ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "heroImageUrl" TEXT;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "businessHours" TEXT;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "mapEmbed" TEXT;
