ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "seoTitle" TEXT;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "seoDescription" TEXT;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "seoKeywords" TEXT;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "seoImageUrl" TEXT;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "seoJsonLd" TEXT;
